# Generated by Django 5.0.2 on 2024-06-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sawah', '0003_city_description_imagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='CityImageModel',
        ),
    ]
