# Generated by Django 5.0.2 on 2024-06-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sawah', '0004_rename_imagemodel_cityimagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelcomment',
            old_name='rating',
            new_name='stars',
        ),
    ]
