# Generated by Django 5.0.2 on 2024-06-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sawah', '0005_rename_rating_hotelcomment_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelcomment',
            old_name='stars',
            new_name='rating',
        ),
    ]
